xavierbriole/react-cookienotice

- README.md
> Fix justifyContent row in readme

- example/src/App.js
- src/Components/AcceptButton.js
- src/Components/CookieIcon.js
- src/Components/CookieNotice.js
- src/Components/CookieText.js
- src/Components/ReadMoreButton.js
> Fix responsive

- README.md
- src/Components/CookieNotice.js
> Add maxWidth prop + remove marginSide prop

- package.json
- src/Components/AcceptButton.js
- src/Components/AcceptButton.test.js
- src/Components/CookieIcon.js
- src/Components/CookieIcon.test.js
- src/Components/CookieNotice.js
- src/Components/CookieNotice.test.js
- src/Components/CookieText.js
- src/Components/CookieText.test.js
- src/Components/ReadMoreButton.js
- src/Components/ReadMoreButton.test.js
- src/Validator/index.js
- src/Validator/validator.js
- src/Validator/validator.test.js
> Added tests + props validator + improve typing

- .flowconfig
- package.json
- src/Components/AcceptButton.js
- src/Components/CookieIcon.js
- src/Components/CookieNotice.js
- src/Components/CookieText.js
- src/Components/ReadMoreButton.js
- src/Helpers/cookies.js
- src/Validator/index.js
- src/Validator/validator.js
- yarn.lock
> Reduce bundle size

- .github/workflows/npm-publish.yml
- .github/workflows/pull-request.yml
- .gitignore
- package.json
> Add codecov + auto changelog

- src/Components/Buttons/AcceptButton.js
- src/Components/Buttons/ReadMoreButton.js
- src/Components/Buttons/index.js
- src/Components/CookieIcon.test.js
- src/Components/CookieNotice.js
- src/Components/CookieText.test.js
- src/Components/Icon.js
- src/Components/Icon.test.js
- src/Components/Text.js
- src/Components/Text.test.js
> Prefix classnames + reword components

- .prettierignore
- package.json
> Update prettier config

- src/Components/Buttons/AcceptButton.test.js
- src/Components/Buttons/ReadMoreButton.test.js
- src/Components/Buttons/index.test.js
- src/Components/CookieNotice.test.js
- src/Components/Icon.test.js
- src/Components/Text.test.js
- src/Components/__snapshots__/CookieNotice.test.js.snap
> Add CookieNotice component tests

- README.md
- src/Components/CookieNotice.js
- src/Components/CookieNotice.test.js
- src/Validator/index.js
- src/Validator/index.test.js
> Add cookieName parameter

- .github/workflows/npm-publish.yml
- README.md
- example/yarn.lock
- package.json
- src/Components/CookieNotice.js
- src/Components/CookieNotice.test.js
> Add new onAcceptButtonClick prop

- .github/workflows/auto-rebase.yml
- .github/workflows/lock-threads.yml
> Add workflows

- .github/workflows/npm-publish.yml
- .github/workflows/pull-request.yml
> Migrate codecov uploader to v2

- .github/workflows/codeql-analysis.yml
- codecov.yml
- package.json
- src/components/__snapshots__/cookie-notice.test.tsx.snap
- src/components/__snapshots__/icon.test.tsx.snap
- src/components/__snapshots__/text.test.tsx.snap
- src/components/buttons/__snapshots__/accept.test.tsx.snap
- src/components/buttons/__snapshots__/index.test.tsx.snap
- src/components/buttons/__snapshots__/read-more.test.tsx.snap
- src/components/buttons/accept.test.tsx
- src/components/buttons/index.test.tsx
- src/components/buttons/read-more.test.tsx
- src/components/cookie-notice.test.tsx
- src/components/cookie-notice.tsx
- src/components/icon.test.tsx
- src/components/text.test.tsx
- src/helpers/cookies.test.ts
- src/helpers/debug.test.ts
- src/helpers/debug.ts
- src/intl/format.test.ts
- yarn.lock
> Add functionals/units tests

- .storybook/main.js
- .storybook/preview.js
- package.json
- src/components/buttons/accept.stories.tsx
- src/components/buttons/index.stories.tsx
- src/components/buttons/read-more.stories.tsx
- src/components/cookie-notice.stories.tsx
- src/components/icon.stories.tsx
- src/components/text.stories.tsx
- yarn.lock
> Add storybook

- .github/workflows/npm-publish.yml
- .github/workflows/pull-request.yml
- .github/workflows/update-coverage.yml
- src/helpers/debug.test.ts
- Add yarn cache for CI (fix #120)
- Improve debug tests
> Add yarn cache for CI

- src/components/__snapshots__/button.test.tsx.snap
- src/components/__snapshots__/cookie-notice.test.tsx.snap
- src/components/__snapshots__/link.test.tsx.snap
- src/components/button.tsx
- src/components/cookie-notice.tsx
- src/components/link.tsx
- src/helpers/classnames.test.ts
- src/helpers/classnames.ts
- src/styles.module.css
> add human readable classnames

- .github/workflows/npm-publish.yml
- .github/workflows/pull-request.yml
- .npmignore
- .yarn/versions/58e29358.yml
- package.json
> Improve CI

- .github/workflows/npm-publish.yml
- .npmignore
- .yarn/versions/6c6a9587.yml
- src/components/cookie-notice.tsx
- tsconfig.json
- remove css import warning
- reduce bundle size (fix #134 )
> Improvements

- package.json
- src/components/cookie-notice.stories.tsx
- [Ignore ts error in sb story](https://github.com/xavierbriole/react-cookienotice/pull/176/commits/648bd05da1b7f8af39d14dcf847189342d21e063)
- [Move ts check into pull-request workflow](https://github.com/xavierbriole/react-cookienotice/pull/176/commits/151e01dbef0140074cd1bcf27a210bc0a15ed50a)
> Some improvements

- README.md
> Add troubleshooting section to README

- README.md
- src/components/__snapshots__/cookie-notice.test.tsx.snap
- src/components/cookie-notice.stories.tsx
- src/components/cookie-notice.test.tsx
- src/components/cookie-notice.tsx
- src/style.css
- src/validator/index.test.ts
- src/validator/index.ts
> fix #192: add position

- .github/workflows/codeql.yml
- .github/workflows/generate-version.yml
- .github/workflows/npm-prerelease-publish.yml
- .github/workflows/npm-release-publish.yml
- .github/workflows/publish-tag.yml
- .github/workflows/run-tests.yml
- .github/workflows/update-coverage.yml
- package.json
> Add npm provenance statement + upgrade actions + upgrade node

- .github/workflows/create-prerelease.yml
- .github/workflows/create-release.yml
- .github/workflows/generate-version.yml
> fix #208: Upgrade some GitHub Actions

- src/components/cookie-notice.test.tsx
- src/components/views/__snapshots__/customize-view.test.tsx.snap
- src/components/views/__snapshots__/service-item.test.tsx.snap
- src/components/views/customize-view.tsx
- src/components/views/service-item.test.tsx
- src/components/views/service-item.tsx
- src/style.css
> feat #215: Accordion in custom view
